version: '3.8'

services:
  celery_worker:
    container_name: cloud_celery_worker
    build: ./worker
    restart: always
    command: "sh -c 'celery -A tasks worker -l info -E'"
    volumes:
      - ./worker:/code
      - ./backend/app/uploads:/code${SHARED_VOLUME_PATH}
    env_file: "./.env"
    environment:
      - C_FORCE_ROOT=true
    expose:
      - 8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: cloud_redis
    ports:
      - 6379:6379

